apply plugin: 'com.android.library'

group = 'com.jagoobahee.lan'
version = '1.0.0'

def expoModulesCorePlugin = new File(
  project(":expo-modules-core").projectDir.absolutePath,
  "ExpoModulesCorePlugin.gradle"
)
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

android {
  namespace "com.jagoobahee.lan"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}
