#!/usr/bin/env node
/**
 * ★ The cross-language canonical gate — P0-G1, the highest-value gate in the project.
 *
 * Runs the TypeScript, Rust and Python dumps over the SAME fixture set and compares them
 * pairwise, byte for byte. Three implementations written against the spec independently;
 * if they all agree, the canonical form is genuinely pinned down rather than being
 * "whatever the TypeScript happens to do today".
 *
 *     node tools/vectors/run-gate.mjs            # verify (CI)
 *     node tools/vectors/run-gate.mjs --update   # rewrite expected.json, then REVIEW IT
 *
 * ── Why pairwise and not "all match expected.json" ──────────────────────────────────
 * expected.json is a convenience for the fast in-language spec. The gate itself never
 * trusts it: it compares the live outputs of three separate implementations against each
 * other. A committed expectation file can be regenerated by a mistake; three independent
 * implementations agreeing on a wrong answer requires the same mistake three times, in
 * three languages, by three different code paths.
 *
 * `--update` is deliberately manual and never runs in CI. Build log L-02: regenerating
 * expectations without reading the diff turns the gate into a rubber stamp.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const EXPECTED = join(HERE, 'expected.json');
// The ESM half of the sdk's dual build: `src/vectors/` uses `import.meta.url` to locate
// the fixture file and so has no CommonJS counterpart by design.
const TS_DUMP = join(ROOT, 'packages', 'sdk-ts', 'dist', 'esm', 'vectors', 'dump.js');

const UPDATE = process.argv.includes('--update');

const red = (s) => `\x1b[31m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;

function run(label, cmd, args, opts = {}) {
  try {
    return execFileSync(cmd, args, {
      cwd: ROOT,
      encoding: 'utf8',
      maxBuffer: 32 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'pipe'],
      ...opts,
    });
  } catch (err) {
    const detail = [err.stderr, err.stdout].filter(Boolean).join('\n').trim();
    throw new Error(`${label} dump failed:\n${detail || err.message}`);
  }
}

/**
 * The TypeScript dump runs from `dist/`, so the build must be current. Building here
 * rather than assuming keeps `pnpm vectors` runnable from a clean checkout.
 */
function ensureTsBuilt() {
  process.stderr.write(dim('  building @jagoo/sdk …\n'));
  run('sdk build', 'pnpm', ['--filter', '@jagoo/sdk', 'build']);
  if (!existsSync(TS_DUMP)) {
    throw new Error(`TypeScript dump missing after build: ${TS_DUMP}`);
  }
}

function collect() {
  ensureTsBuilt();

  process.stderr.write(dim('  running typescript …\n'));
  const ts = JSON.parse(run('typescript', process.execPath, [TS_DUMP]));

  process.stderr.write(dim('  running rust …\n'));
  const rust = JSON.parse(
    run('rust', 'cargo', ['run', '--quiet', '-p', 'jb-core', '--bin', 'jb-dump']),
  );

  process.stderr.write(dim('  running python …\n'));
  const python = JSON.parse(run('python', 'python3', [join(HERE, 'dump.py')]));

  return { typescript: ts, rust, python };
}

/** Every disagreement, not just the first — one run should show the whole picture. */
function diff(nameA, a, nameB, b) {
  const failures = [];
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);

  for (const key of [...keys].sort()) {
    if (!(key in a)) {
      failures.push(`  ${key}: missing from ${nameA}`);
      continue;
    }
    if (!(key in b)) {
      failures.push(`  ${key}: missing from ${nameB}`);
      continue;
    }
    for (const field of ['canonical_hex', 'content_id']) {
      if (a[key][field] !== b[key][field]) {
        failures.push(
          `  ${key}.${field}\n` +
            `    ${nameA.padEnd(10)} ${a[key][field]}\n` +
            `    ${nameB.padEnd(10)} ${b[key][field]}`,
        );
      }
    }
  }
  return failures;
}

function main() {
  process.stderr.write('★ cross-language canonical gate (P0-G1)\n');

  const dumps = collect();
  const langs = Object.keys(dumps);
  const count = Object.keys(dumps.typescript).length;

  const failures = [];
  for (let i = 0; i < langs.length; i += 1) {
    for (let j = i + 1; j < langs.length; j += 1) {
      failures.push(...diff(langs[i], dumps[langs[i]], langs[j], dumps[langs[j]]));
    }
  }

  if (failures.length > 0) {
    process.stderr.write(red(`\n✗ ${failures.length} disagreement(s) across implementations\n\n`));
    process.stderr.write(`${failures.join('\n')}\n\n`);
    process.stderr.write(
      'The canonical form is the contract. Fix the implementation that is wrong —\n' +
        'do NOT regenerate expected.json to make this pass.\n',
    );
    process.exit(1);
  }

  process.stderr.write(green(`  ✓ ${langs.length} implementations agree on ${count} vectors\n`));

  // All three agree, so their shared answer is the authority for expected.json.
  const canonical = JSON.stringify(dumps.typescript, null, 2) + '\n';

  if (UPDATE) {
    writeFileSync(EXPECTED, canonical);
    process.stderr.write(green(`  ✓ wrote ${EXPECTED}\n`));
    process.stderr.write('    REVIEW THE DIFF BY HAND before committing (build log L-02).\n');
    return;
  }

  if (!existsSync(EXPECTED)) {
    process.stderr.write(red('\n✗ expected.json is missing. Run: pnpm vectors --update\n'));
    process.exit(1);
  }

  if (readFileSync(EXPECTED, 'utf8') !== canonical) {
    const stored = JSON.parse(readFileSync(EXPECTED, 'utf8'));
    process.stderr.write(red('\n✗ expected.json disagrees with all three implementations\n\n'));
    process.stderr.write(`${diff('expected', stored, 'actual', dumps.typescript).join('\n')}\n\n`);
    process.stderr.write(
      'Three implementations agree with each other and disagree with the committed\n' +
        'expectation. Either the encoding changed deliberately — in which case run\n' +
        '`pnpm vectors --update`, review the diff, and note the change in BUILD-LOG.md —\n' +
        'or something regressed in a way all three share.\n',
    );
    process.exit(1);
  }

  process.stderr.write(green('  ✓ expected.json matches\n'));
  process.stderr.write(green('\n★ P0-G1 PASS\n'));
}

main();
