#!/usr/bin/env node
/**
 * ★ The cross-language canonical gate — P0-G1, the highest-value gate in the project.
 *
 * Runs the TypeScript, Rust and Python dumps over the SAME fixture set and compares them
 * pairwise, byte for byte. Three implementations written against the spec independently;
 * if they all agree, the canonical form is genuinely pinned down rather than being
 * "whatever the TypeScript happens to do today".
 *
 *     node tools/vectors/run-gate.mjs            # verify (CI)
 *     node tools/vectors/run-gate.mjs --update   # rewrite expected.json, then REVIEW IT
 *
 * ── Why pairwise and not "all match expected.json" ──────────────────────────────────
 * expected.json is a convenience for the fast in-language spec. The gate itself never
 * trusts it: it compares the live outputs of three separate implementations against each
 * other. A committed expectation file can be regenerated by a mistake; three independent
 * implementations agreeing on a wrong answer requires the same mistake three times, in
 * three languages, by three different code paths.
 *
 * `--update` is deliberately manual and never runs in CI. Build log L-02: regenerating
 * expectations without reading the diff turns the gate into a rubber stamp.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { delimiter, dirname, join } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const WINDOWS = process.platform === 'win32';
const EXPECTED = join(HERE, 'expected.json');
// The ESM half of the sdk's dual build: `src/vectors/` uses `import.meta.url` to locate
// the fixture file and so has no CommonJS counterpart by design.
const TS_DUMP = join(ROOT, 'packages', 'sdk-ts', 'dist', 'esm', 'vectors', 'dump.js');

const UPDATE = process.argv.includes('--update');

const red = (s) => `\x1b[31m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;

function run(label, cmd, args, opts = {}) {
  try {
    return execFileSync(cmd, args, {
      cwd: ROOT,
      encoding: 'utf8',
      maxBuffer: 32 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'pipe'],
      ...opts,
    });
  } catch (err) {
    const detail = [err.stderr, err.stdout].filter(Boolean).join('\n').trim();
    throw new Error(`${label} dump failed:\n${detail || err.message}`);
  }
}

/**
 * Locate an executable without relying on a shell.
 *
 * Node >= 20.19 refuses to execFile a Windows `.cmd`/`.bat` without `shell: true` (the
 * fix for CVE-2024-27980), and a bare `cargo`/`python3` is simply absent on a default
 * Windows PATH. Resolving explicitly keeps the gate spawning real binaries on both
 * platforms rather than failing with ENOENT and looking like a tooling problem.
 */
function which(candidates, extraDirs = []) {
  const pathDirs = (process.env.PATH ?? '').split(delimiter).filter(Boolean);
  const exts = WINDOWS ? ['.exe', '.cmd', '.bat', ''] : [''];

  for (const dir of [...extraDirs, ...pathDirs]) {
    for (const name of candidates) {
      for (const ext of exts) {
        const candidate = join(dir, name + ext);
        if (existsSync(candidate)) return candidate;
      }
    }
  }
  return null;
}

function requireTool(label, candidates, extraDirs, hint) {
  const found = which(candidates, extraDirs);
  if (!found) {
    throw new Error(
      `${label} not found (looked for ${candidates.join(', ')}).\n` +
        `  This gate needs all three implementations — it cannot be satisfied by skipping one.\n` +
        `  ${hint}`,
    );
  }
  return found;
}

const CARGO = () =>
  requireTool(
    'cargo',
    ['cargo'],
    [join(homedir(), '.cargo', 'bin')],
    'Install Rust from https://rustup.rs and ensure ~/.cargo/bin is on PATH.',
  );

const PYTHON = () =>
  requireTool(
    'python',
    WINDOWS ? ['python', 'python3'] : ['python3', 'python'],
    [],
    'Install Python 3.10+ and ensure it is on PATH.',
  );

/**
 * The TypeScript dump runs from `dist/`, so the build must be current. Building here
 * rather than assuming keeps `pnpm vectors` runnable from a clean checkout.
 *
 * `npm_execpath` is the package manager's own JS entry, set whenever this script is run
 * through `pnpm vectors`. Running it under the current Node binary avoids spawning the
 * `pnpm.cmd` shim, which Node would refuse without a shell.
 */
function ensureTsBuilt() {
  process.stderr.write(dim('  building @jagoo/sdk …\n'));

  const execPath = process.env.npm_execpath;
  if (execPath && execPath.endsWith('.cjs')) {
    run('sdk build', process.execPath, [execPath, '--filter', '@jagoo/sdk', 'build']);
  } else {
    const pnpm = requireTool(
      'pnpm',
      ['pnpm'],
      [],
      'Run this through `pnpm vectors`, or install pnpm 9 via `corepack enable pnpm`.',
    );
    run('sdk build', pnpm, ['--filter', '@jagoo/sdk', 'build'], { shell: WINDOWS });
  }

  if (!existsSync(TS_DUMP)) {
    throw new Error(`TypeScript dump missing after build: ${TS_DUMP}`);
  }
}

function collect() {
  ensureTsBuilt();

  process.stderr.write(dim('  running typescript …\n'));
  const ts = JSON.parse(run('typescript', process.execPath, [TS_DUMP]));

  process.stderr.write(dim('  running rust …\n'));
  const rust = JSON.parse(
    run('rust', CARGO(), ['run', '--quiet', '-p', 'jb-core', '--bin', 'jb-dump']),
  );

  process.stderr.write(dim('  running python …\n'));
  const python = JSON.parse(run('python', PYTHON(), [join(HERE, 'dump.py')]));

  return { typescript: ts, rust, python };
}

/** Every disagreement, not just the first — one run should show the whole picture. */
function diff(nameA, a, nameB, b) {
  const failures = [];
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);

  for (const key of [...keys].sort()) {
    if (!(key in a)) {
      failures.push(`  ${key}: missing from ${nameA}`);
      continue;
    }
    if (!(key in b)) {
      failures.push(`  ${key}: missing from ${nameB}`);
      continue;
    }
    for (const field of ['canonical_hex', 'content_id']) {
      if (a[key][field] !== b[key][field]) {
        failures.push(
          `  ${key}.${field}\n` +
            `    ${nameA.padEnd(10)} ${a[key][field]}\n` +
            `    ${nameB.padEnd(10)} ${b[key][field]}`,
        );
      }
    }
  }
  return failures;
}

function main() {
  process.stderr.write('★ cross-language canonical gate (P0-G1)\n');

  const dumps = collect();
  const langs = Object.keys(dumps);
  const count = Object.keys(dumps.typescript).length;

  const failures = [];
  for (let i = 0; i < langs.length; i += 1) {
    for (let j = i + 1; j < langs.length; j += 1) {
      failures.push(...diff(langs[i], dumps[langs[i]], langs[j], dumps[langs[j]]));
    }
  }

  if (failures.length > 0) {
    process.stderr.write(red(`\n✗ ${failures.length} disagreement(s) across implementations\n\n`));
    process.stderr.write(`${failures.join('\n')}\n\n`);
    process.stderr.write(
      'The canonical form is the contract. Fix the implementation that is wrong —\n' +
        'do NOT regenerate expected.json to make this pass.\n',
    );
    process.exit(1);
  }

  process.stderr.write(green(`  ✓ ${langs.length} implementations agree on ${count} vectors\n`));

  // All three agree, so their shared answer is the authority for expected.json.
  const canonical = JSON.stringify(dumps.typescript, null, 2) + '\n';

  if (UPDATE) {
    writeFileSync(EXPECTED, canonical);
    process.stderr.write(green(`  ✓ wrote ${EXPECTED}\n`));
    process.stderr.write('    REVIEW THE DIFF BY HAND before committing (build log L-02).\n');
    return;
  }

  if (!existsSync(EXPECTED)) {
    process.stderr.write(red('\n✗ expected.json is missing. Run: pnpm vectors --update\n'));
    process.exit(1);
  }

  // Git may check text files out as CRLF on Windows. JSON semantics and canonical bytes
  // are unchanged, so line-ending policy must not make the cross-language gate fail.
  const expectedText = readFileSync(EXPECTED, 'utf8').replaceAll('\r\n', '\n');
  if (expectedText !== canonical) {
    const stored = JSON.parse(expectedText);
    process.stderr.write(red('\n✗ expected.json disagrees with all three implementations\n\n'));
    process.stderr.write(`${diff('expected', stored, 'actual', dumps.typescript).join('\n')}\n\n`);
    process.stderr.write(
      'Three implementations agree with each other and disagree with the committed\n' +
        'expectation. Either the encoding changed deliberately — in which case run\n' +
        '`pnpm vectors --update`, review the diff, and note the change in BUILD-LOG.md —\n' +
        'or something regressed in a way all three share.\n',
    );
    process.exit(1);
  }

  process.stderr.write(green('  ✓ expected.json matches\n'));
  process.stderr.write(green('\n★ P0-G1 PASS\n'));
}

main();
