# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jagoo.v1 import bridge_pb2 as jagoo_dot_v1_dot_bridge__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jagoo/v1/bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReticulumBridgeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Announce = channel.unary_unary(
                '/jagoo.v1.ReticulumBridge/Announce',
                request_serializer=jagoo_dot_v1_dot_bridge__pb2.BridgeAnnounceReq.SerializeToString,
                response_deserializer=jagoo_dot_v1_dot_bridge__pb2.BridgeAnnounceResp.FromString,
                _registered_method=True)
        self.Send = channel.unary_unary(
                '/jagoo.v1.ReticulumBridge/Send',
                request_serializer=jagoo_dot_v1_dot_bridge__pb2.SendReq.SerializeToString,
                response_deserializer=jagoo_dot_v1_dot_bridge__pb2.SendResp.FromString,
                _registered_method=True)
        self.Receive = channel.unary_stream(
                '/jagoo.v1.ReticulumBridge/Receive',
                request_serializer=jagoo_dot_v1_dot_bridge__pb2.ReceiveReq.SerializeToString,
                response_deserializer=jagoo_dot_v1_dot_bridge__pb2.InboundEnvelope.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/jagoo.v1.ReticulumBridge/Status',
                request_serializer=jagoo_dot_v1_dot_bridge__pb2.StatusReq.SerializeToString,
                response_deserializer=jagoo_dot_v1_dot_bridge__pb2.BridgeStatus.FromString,
                _registered_method=True)


class ReticulumBridgeServicer:
    """Missing associated documentation comment in .proto file."""

    def Announce(self, request, context):
        """Publish a destination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Class 0-2 only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Receive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReticulumBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Announce': grpc.unary_unary_rpc_method_handler(
                    servicer.Announce,
                    request_deserializer=jagoo_dot_v1_dot_bridge__pb2.BridgeAnnounceReq.FromString,
                    response_serializer=jagoo_dot_v1_dot_bridge__pb2.BridgeAnnounceResp.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=jagoo_dot_v1_dot_bridge__pb2.SendReq.FromString,
                    response_serializer=jagoo_dot_v1_dot_bridge__pb2.SendResp.SerializeToString,
            ),
            'Receive': grpc.unary_stream_rpc_method_handler(
                    servicer.Receive,
                    request_deserializer=jagoo_dot_v1_dot_bridge__pb2.ReceiveReq.FromString,
                    response_serializer=jagoo_dot_v1_dot_bridge__pb2.InboundEnvelope.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=jagoo_dot_v1_dot_bridge__pb2.StatusReq.FromString,
                    response_serializer=jagoo_dot_v1_dot_bridge__pb2.BridgeStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jagoo.v1.ReticulumBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jagoo.v1.ReticulumBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReticulumBridge:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jagoo.v1.ReticulumBridge/Announce',
            jagoo_dot_v1_dot_bridge__pb2.BridgeAnnounceReq.SerializeToString,
            jagoo_dot_v1_dot_bridge__pb2.BridgeAnnounceResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jagoo.v1.ReticulumBridge/Send',
            jagoo_dot_v1_dot_bridge__pb2.SendReq.SerializeToString,
            jagoo_dot_v1_dot_bridge__pb2.SendResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Receive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jagoo.v1.ReticulumBridge/Receive',
            jagoo_dot_v1_dot_bridge__pb2.ReceiveReq.SerializeToString,
            jagoo_dot_v1_dot_bridge__pb2.InboundEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jagoo.v1.ReticulumBridge/Status',
            jagoo_dot_v1_dot_bridge__pb2.StatusReq.SerializeToString,
            jagoo_dot_v1_dot_bridge__pb2.BridgeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
