/**
 * The unreachable node's half of the reverse tunnel (T3.17, TP-16).
 *
 * Polls a `TRUSTED` peer for client requests addressed to this node, executes each against
 * this node's own local HTTP surface, and posts the response back. Every connection is
 * OUTBOUND — that is the entire point, and it is why this works behind CGNAT where no port
 * forward can.
 *
 * ── Failure is expected and must be quiet ──────────────────────────────────────────
 * The exit peer will be unreachable sometimes; that is what a shutdown looks like. The loop
 * backs off and retries rather than crashing the node, because a node whose tunnel is down is
 * still a fully functional federation participant (FD-11) and still serves its own LAN.
 */

import { federationCallAuthBytes } from '@jagoo/sdk';
import type {
  TunnelJob,
  TunnelResponse,
} from '../../../core/app/reverse-tunnel.js';
import type { NodeSigner } from '../../../core/ports/node-signer.port.js';
import type { Clock, RandomSource } from '../../../core/ports/system.port.js';

export interface ReverseTunnelClientDeps {
  readonly signer: NodeSigner;
  readonly clock: Clock;
  readonly random: RandomSource;
  /** The `TRUSTED` peer's HTTP origin, e.g. `https://relay.example.org`. */
  readonly exitOrigin: string;
  /** This node's own HTTP origin, which the tunnelled request is replayed against. */
  readonly localOrigin: string;
  readonly pollTimeoutMs?: number;
  readonly fetchImpl?: typeof fetch;
}

const RETRY_BASE_MS = 1_000;
const RETRY_MAX_MS = 30_000;

export class ReverseTunnelClient {
  private running = false;
  private failures = 0;

  constructor(private readonly deps: ReverseTunnelClientDeps) {}

  start(): void {
    if (this.running) return;
    this.running = true;
    void this.loop();
  }

  stop(): void {
    this.running = false;
  }

  get connected(): boolean {
    return this.running && this.failures === 0;
  }

  private async loop(): Promise<void> {
    while (this.running) {
      try {
        const job = await this.poll();
        this.failures = 0;
        if (job) await this.serve(job);
      } catch {
        this.failures += 1;
        await sleep(
          Math.min(RETRY_BASE_MS * 2 ** Math.min(this.failures - 1, 5), RETRY_MAX_MS),
        );
      }
    }
  }

  private async poll(): Promise<TunnelJob | null> {
    const doFetch = this.deps.fetchImpl ?? fetch;
    const response = await doFetch(`${this.deps.exitOrigin}/v1/tunnel/poll`, {
      method: 'GET',
      headers: this.authHeaders('TunnelPoll'),
      signal: AbortSignal.timeout((this.deps.pollTimeoutMs ?? 30_000) + 5_000),
    });
    if (response.status === 204) return null;
    if (!response.ok) throw new Error(`tunnel poll failed: HTTP ${response.status}`);
    return (await response.json()) as TunnelJob;
  }

  /**
   * Replay the request locally, then post the answer back.
   *
   * The local call goes to `127.0.0.1` — this node's own server — so the response is
   * generated by exactly the code a directly-connected client would have reached. A tunnel
   * that re-implemented any part of the request handling would be a second, divergent
   * surface, and the divergence would only show up during the outage.
   */
  private async serve(job: TunnelJob): Promise<void> {
    const doFetch = this.deps.fetchImpl ?? fetch;
    let result: TunnelResponse;
    try {
      const upstream = await doFetch(`${this.deps.localOrigin}${job.path}`, {
        method: job.method,
        headers: job.headers,
        ...(job.body === undefined
          ? {}
          : { body: Buffer.from(job.body, 'base64') as unknown as BodyInit }),
        signal: AbortSignal.timeout(15_000),
      });
      const body = Buffer.from(await upstream.arrayBuffer()).toString('base64');
      const headers: Record<string, string> = {};
      upstream.headers.forEach((value, key) => {
        headers[key] = value;
      });
      result = { id: job.id, status: upstream.status, headers, body };
    } catch (error) {
      result = {
        id: job.id,
        status: 502,
        headers: { 'content-type': 'application/json' },
        body: Buffer.from(
          JSON.stringify({
            error: error instanceof Error ? error.message : 'local request failed',
          }),
          'utf8',
        ).toString('base64'),
      };
    }

    await doFetch(`${this.deps.exitOrigin}/v1/tunnel/respond`, {
      method: 'POST',
      headers: { ...this.authHeaders('TunnelRespond'), 'content-type': 'application/json' },
      body: JSON.stringify(result),
      signal: AbortSignal.timeout(10_000),
    });
  }

  /**
   * The same signed, method-bound, time-bound claim the gRPC calls carry, over HTTP headers.
   *
   * Reused rather than reinvented: a bare `jb-peer-id` header would let any caller claim any
   * node's tunnel and receive its clients' traffic, which is the one thing this feature must
   * not permit.
   */
  private authHeaders(method: string): Record<string, string> {
    const nowMs = this.deps.clock.nowMs();
    const nonce = this.deps.random.bytes(16);
    const signature = this.deps.signer.sign(
      federationCallAuthBytes(method, BigInt(nowMs), nonce),
    );
    return {
      'jb-peer-key': Buffer.from(this.deps.signer.publicKey).toString('base64'),
      'jb-peer-ts': String(nowMs),
      'jb-peer-nonce': Buffer.from(nonce).toString('base64'),
      'jb-peer-auth': Buffer.from(signature).toString('base64'),
    };
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => {
    const timer = setTimeout(resolve, ms);
    timer.unref?.();
  });
}
