/**
 * T0.14 / P0-G1 — the canonical encoder agrees with the committed expectations.
 *
 * ── Why this is not circular (build log L-02) ────────────────────────────────────────
 * `expected.json` is NOT generated by this implementation. `pnpm vectors` regenerates it
 * only after Rust and Python independently agree, and the diff is reviewed by hand. So a
 * TypeScript-only bug cannot update its own expectation — it has to convince two other
 * implementations first. A test that asserts against a hash its own code produced proves
 * only that the code agrees with itself.
 *
 * This spec is the fast in-language guard. The real cross-language comparison is
 * `pnpm vectors`, which runs all three dumps and diffs them pairwise.
 *
 * Specification: Plans/02-CONTRACTS-CORE.md §1–2
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { bytesToHex } from '@noble/hashes/utils';
import { canonicalBytes } from '../core/canonical.js';
import { contentIdFromCanonical, isContentId } from '../core/content-id.js';
import { encodeUtf8Nfc } from '../core/wire.js';
import { envelopeFromFixture, loadVectors, workspaceRoot } from './fixtures.js';

interface Expectation {
  readonly canonical_hex: string;
  readonly content_id: string;
}

const EXPECTED_PATH = join(workspaceRoot(), 'tools', 'vectors', 'expected.json');
const expected = JSON.parse(readFileSync(EXPECTED_PATH, 'utf8')) as Record<string, Expectation>;

const vectors = loadVectors();

describe('canonical encoding (P0-G1)', () => {
  it('has an expectation for every fixture, and no orphans', () => {
    expect(Object.keys(expected).sort()).toEqual(vectors.map((v) => v.name).sort());
  });

  for (const v of vectors) {
    it(`${v.name} — ${v.description.slice(0, 72)}`, () => {
      const canonical = canonicalBytes(envelopeFromFixture(v.envelope));
      const want = expected[v.name];
      expect(want, `no expectation for ${v.name}`).toBeDefined();
      expect(bytesToHex(canonical)).toBe(want!.canonical_hex);
      expect(contentIdFromCanonical(canonical)).toBe(want!.content_id);
    });
  }

  it('every content ID is well-formed (jb1 + 52 base32 chars)', () => {
    for (const v of vectors) {
      const id = contentIdFromCanonical(canonicalBytes(envelopeFromFixture(v.envelope)));
      expect(isContentId(id), `${v.name} produced ${id}`).toBe(true);
    }
  });
});

describe('EN-01 rule 2 — an empty AntiAbuse is omitted, not emitted as a zero-length message', () => {
  // Proto3 would allow either `{}` set or unset. Allowing both would be a second accepted
  // form, which is exactly the ambiguity EN-02 forecloses. All three languages implement
  // the identical rule, so these two fixtures must be indistinguishable on the wire.
  it('anti-abuse-absent and anti-abuse-empty-object encode identically', () => {
    const absent = canonicalBytes(envelopeFromFixture(vectorNamed('anti-abuse-absent').envelope));
    const empty = canonicalBytes(
      envelopeFromFixture(vectorNamed('anti-abuse-empty-object').envelope),
    );
    expect(bytesToHex(absent)).toBe(bytesToHex(empty));
  });
});

describe('EN-01 rule 4 — strings are NFC-normalised before encoding', () => {
  // The same Bangla text composed and decomposed must land on identical bytes, or two
  // devices with different input methods would produce different content IDs for the
  // same post and federation would silently duplicate it.
  it('nfc-composed and nfc-decomposed encode identically', () => {
    const composed = canonicalBytes(envelopeFromFixture(vectorNamed('nfc-composed').envelope));
    const decomposed = canonicalBytes(envelopeFromFixture(vectorNamed('nfc-decomposed').envelope));
    expect(bytesToHex(composed)).toBe(bytesToHex(decomposed));
  });
});

describe('Bangla NFC — the size budgets depend on this (NFR-A04, SIG-26)', () => {
  // U+09DC RRA, U+09DD RHA and U+09DF YYA are Unicode *composition exclusions*: NFC does
  // not recompose base + nukta, so a precomposed 'ড়' normalises DOWN to two code points
  // and costs 6 bytes, not 3.
  //
  // This is load-bearing. Class 0-2 budgets (broadcast <= 512 B after encoding, including
  // signature and anti-abuse) are computed against the Bangla worst case, and these are
  // high-frequency letters, not exotica. Sizing at "3 bytes per visible character"
  // under-counts real Bangla text — a broadcast that fits in the lab and is rejected at
  // construction in the field.
  //
  // TypeScript is the production implementation on both backend and frontend, so its NFC
  // must agree with the Rust and Python references exactly. It does: 31 / 6 / 3.
  it('a precomposed nukta letter survives NFC as two code points', () => {
    expect(encodeUtf8Nfc('ড়')).toEqual(encodeUtf8Nfc('ড়'));
    expect(encodeUtf8Nfc('ড়').length).toBe(6);
    expect(encodeUtf8Nfc('ড').length).toBe(3);
  });

  it('"পানি বাড়ছে" (water is rising) is 31 bytes, not 28', () => {
    expect(encodeUtf8Nfc('পানি বাড়ছে').length).toBe(31);
  });
});

describe('EN-01 rule 5 / int64 exactness', () => {
  it('a timestamp above 2^53 survives encoding exactly', () => {
    const v = vectorNamed('large-timestamp');
    const env = envelopeFromFixture(v.envelope);
    expect(env.created_at_ms).toBe(BigInt(v.envelope.created_at_ms!));
    expect(bytesToHex(canonicalBytes(env))).toBe(expected['large-timestamp']!.canonical_hex);
  });
});

function vectorNamed(name: string) {
  const found = vectors.find((v) => v.name === name);
  if (!found) throw new Error(`fixture vector not found: ${name}`);
  return found;
}
